---
title: "HTO Report"
author: "Quanhu Sheng"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmdformats::readthedown:
    toc_depth: 3
---

```{r global options, include = FALSE}
knitr::opts_chunk$set(echo=TRUE, include=TRUE, warning=FALSE, message=FALSE)
```

```{css, echo=FALSE}
#content{
    max-width:1920px;
}
```

```{r setup}
library(Seurat)
library(ggplot2)
library(patchwork)
library(kableExtra)
library(dplyr)
library(mclust)

theme_bw3 <- function () { 
	theme_bw() +
	theme(
		strip.background = element_rect(fill = NA, colour = 'black'),
		panel.border = element_rect(fill = NA, color = "black"),			
		axis.line = element_line(colour = "black", size = 0.5)
	)
}

source("C:/Users/sheng/Programs/projects/papers/20210703_scrna_hto/split_samples_utils_lch.r")
```

```{r}
prepare_data<-function(name){
  rds_file=paste0("C:/projects/scratch/cqs/shengq2/papers/20221116_scrna_hto/", name, "/", name, ".results_obj.rds")

  htos<-readRDS(rds_file)

  glist<-list()
  meta<-htos@meta.data

  htocols<-c("scDemultiplex_cutoff", "scDemultiplex_refine", "Seurat_HTODemux", "Seurat_MULTIseqDemux", "GMM_demux")
  col=htocols[1]
  for(col in htocols){
    newcol.global.name<-paste0(col, ".global")
    newcol.global<-as.character(meta[,col])
    newcol.global[!newcol.global %in% c("Negative", "Doublet")]<-"Singlet"
    htos<-AddMetaData(htos, newcol.global, col.name = newcol.global.name)

    glist[[col]] = DimPlot(htos, reduction="umap", group.by=col) + ggtitle(col) 

    celllist<-list()
    celllist$Negative<-colnames(htos)[newcol.global == "Negative"]
    celllist$Doublet<-colnames(htos)[newcol.global == "Doublet"]
    cellcolors<-list()
    cellcolors$Negative<-"Blue"
    cellcolors$Doublet<-"Red"
  
    glist[[newcol.global.name]] = DimPlot(htos, reduction="umap", cells.highlight = celllist, cols.highlight = cellcolors, group.by=newcol.global.name) + ggtitle(col)   
  }
  
  g<-wrap_plots(glist, ncol=2)
  return(list(htos=htos, htocols=htocols, g=g))
}
```

```{r}

process_data<-function(name){
  cat("#", name, "\n\n")
  hto_list<-prepare_data(name)
  obj<-hto_list$htos
  meta<-obj@meta.data
  meta$log_nCount_HTO<-log2(meta$nCount_HTO + 1)

  cat("## Four HTO classifications\n\n")
  print(hto_list$g)
  
  alltb<-NULL
  for (col in hto_list$htocols){
    coltb<-table(meta[,col])
    alltb<-rbind(alltb, coltb)  
  }
  rownames(alltb)<-hto_list$htocols
  tbl<-alltb %>%
    kbl() %>%
    kable_paper("hover", full_width = T)  
  print(tbl)
  
  cat("### DE analysis\n\n")
  alltb<-NULL
  col<-hto_list$htocols[2]
  for (col in hto_list$htocols){
    #singlet<-colnames(obj)[!(meta[,col] %in% c("Negative", "Doublet"))]
    #subobj<-subset(obj, cells=singlet)
    subobj<-obj
    Idents(subobj)<-col
    markers<-FindAllMarkers(subobj, pseudocount.use = FALSE,only.pos = TRUE)
    markers<-markers[!(markers$cluster %in% c("Negative", "Doublet")),]
    markers<-markers[order(markers$gene),c("gene", "avg_log2FC"), drop=F]
    rownames(markers)<-markers$gene
    markers<-markers[,"avg_log2FC", drop=F]
    colnames(markers)=col
    if(is.null(alltb)){
      alltb<-markers
    }else{
      alltb<-cbind(alltb, markers)
    }
  }
  tbl<-t(alltb) %>%
    kbl() %>%
    kable_paper("hover", full_width = T)  
  print(tbl)
  

  cat("### log_nCount_HTO \n\n")
  hto="Negative"
  for (hto in c("Negative", "Doublet")){
    cat("\n\n#### ", hto, "\n\n")
    alltf<-NULL
    col = hto_list$htocols[1]
    for (col in hto_list$htocols){
      tt<-meta[meta[,col] == hto, "log_nCount_HTO", drop=F]
      tt$method = col
      alltf<-rbind(alltf, tt)
    }  
    alltf$method<-factor(alltf$method, levels=hto_list$htocols)
    g<-ggplot(alltf, aes_string("method", "log_nCount_HTO")) + geom_violin() + geom_boxplot(width=0.2, outlier.shape = NA) + theme_bw3() + xlab("") + ylab("log(nCount_HTO)") + ggtitle(hto)
    print(g)
  }  
  
  cat("\n\n### refinement vs cutoff\n\n")
  t1<-"scDemultiplex_cutoff"
  t2<-"scDemultiplex_refine"
  
  cat("\n\n#### Negative\n\n")
  wt<-wilcox.test(meta$nCount_HTO[meta[,t1] == "Negative"], meta$nCount_HTO[meta[,t2] == "Negative"])
  cat("Wilcox test pvalue=", wt$p.value, "\n\n")

  cat("\n\n#### Changed cells from Negative\n\n")  
  tt<-meta[meta[,t1] == "Negative",]
  g<-ggplot(tt, aes_string(t2, "log_nCount_HTO")) + geom_violin() + geom_boxplot(width=0.2, outlier.shape = NA) + geom_jitter(width = 0.2) + theme_bw3()
  print(g)

  cat("\n\n#### Doublet\n\n")
  wt<-wilcox.test(meta$nCount_HTO[meta[,t1] == "Doublet"], meta$nCount_HTO[meta[,t2] == "Doublet"])
  cat("Wilcox test pvalue=", wt$p.value, "\n\n")

  cat("\n\n#### Changed cells from Doublet\n\n")  

  tt<-meta[meta[,t1] == "Doublet",]
  g<-ggplot(tt, aes_string(t2, "log_nCount_HTO")) + geom_violin() + geom_boxplot(width=0.2, outlier.shape = NA) + geom_jitter(width = 0.2) + theme_bw3()
  print(g)
  
  if(name == "hto12_old"){
    hto12_combined_obj_rds<-r"(C:\projects\data\cqs\seurat_data\hto12_combined_obj.rds)"
    if(file.exists(hto12_combined_obj_rds)){
      obj<-readRDS(hto12_combined_obj_rds)
    }else{
      umi = readRDS(r"(C:\projects\data\cqs\seurat_data\hto12_umi_mtx.rds)")
      umi<-umi[, colnames(obj)]
      obj[["RNA"]] <- CreateAssayObject(counts = umi)
      DefaultAssay(obj)<-"RNA"
      # Normalize RNA data with log normalization
      obj <- NormalizeData(obj)
      # Find and scale variable features
      obj <- FindVariableFeatures(obj, selection.method = "mean.var.plot")
      features = VariableFeatures(obj)
      obj <- ScaleData(obj, features = features)    
      obj <- RunPCA(obj, features = features)
      obj <- RunUMAP(obj, reduction = "pca", dims=1:20)
      obj <- FindNeighbors(obj, reduction = "pca")
      obj <- FindClusters(obj, reduction = "pca") 
      saveRDS(obj, hto12_combined_obj_rds)
    }
    
    ari_list=list()
    col=hto_list$htocols[1]
    for(col in hto_list$htocols){
      ari=adjustedRandIndex(obj$seurat_clusters, unlist(FetchData(obj, col)))
      ari_list[[col]] = ari
    }
    ari_df<-t(data.frame(ari_list))
    colnames(ari_df)<-"ari"
    cat("\n\n#### AdjustRandIndex\n\n")
    tbl<-ari_df %>%
      kbl() %>%
      kable_paper("hover", full_width = T)  
    print(tbl)

    glist=list()
    newcols=c()
    for(col in hto_list$htocols){
      newcol = paste0(col, "_celltype")
      newcolvalue = gsub("-.", "", unlist(FetchData(obj, col)))
      cts<-sort(unique(newcolvalue))      
      obj<-AddMetaData(obj, newcolvalue, col.name = newcol)
      newcols<-c(newcols, newcol)
      glist[[col]] = DimPlot(obj, reduction = "umap", group.by=newcol) + ggtitle(col)
    }
    
    ct=cts[1]
    for(ct in cts){
      for(newcol in newcols){
        newcolvalue = unlist(FetchData(obj, newcol))
        cells<-colnames(obj)[newcolvalue == ct]
        gname = paste0(newcol, ":", ct)
        g<-DimPlot(obj, reduction = "umap", cells.highlight = cells, cols.highlight = "red") + ggtitle(gname)
        glist[[gname]] = g
      }
    }
    
    gg<-wrap_plots(glist, ncol=length(newcols))
    return(gg)
  }else{
    return(NULL)
  }
}
```

```{r results="asis", fig.height=15, fig.width=15}
gg<-process_data("hto12")
```

```{r results="asis", fig.height=28, fig.width=16}
#print(gg)
```

```{r results="asis", fig.height=15, fig.width=15}
process_data("pbmc")
```
